name: vybgo
description: VYBGO ride-hailing app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  http: ^1.1.0
  shared_preferences: ^2.2.2
  just_audio: ^0.9.36
  path_provider: ^2.1.2
  supabase_flutter: ^2.3.4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  path_provider_foundation: ^2.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/


